program for inserting space between characters of all elements in a NumPy array

In [6]:
import numpy as np

# Create a NumPy array of strings
original_array = np.array(['abc', 'def', 'ghi'])

# Insert space between characters in each element
array_with_spaces = np.array([' '.join(list(element)) for element in original_array])

# Print the results
print("Original Array:")
print(original_array)

print("\nArray with Spaces:")
print(array_with_spaces)


Original Array:
['abc' 'def' 'ghi']

Array with Spaces:
['a b c' 'd e f' 'g h i']


Repeat each element 5 times in an array

In [9]:
import numpy as np

# Create a NumPy array
original_array = np.array([1, 2, 3, 4, 5])

# Repeat each element five times
repeated_array = np.repeat(original_array, 5)

# Repeat sequence
sequence_repeated_array = np.tile(original_array, 5)

# Print the results
print("Original Array:")
print(original_array)

print("\nArray with Elements Repeated Five Times:")
print(repeated_array)

print("\nArray Repeated in Sequence:")
print(sequence_repeated_array)


Original Array:
[1 2 3 4 5]

Array with Elements Repeated Five Times:
[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 5 5 5 5 5]

Array Repeated in Sequence:
[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]


Swapping axes in a matrix

In [27]:
import numpy as np

# Create a 2D array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Interchange the axes
interchanged_array = np.swapaxes(original_array, 0, 1)

# Print the results
print("Original 2D Array:")
print(original_array)

print("\nInterchanged 2D Array:")
print(interchanged_array)


Original 2D Array:
[[1 2 3]
 [4 5 6]]

Interchanged 2D Array:
[[1 4]
 [2 5]
 [3 6]]


In [28]:
#or
transposed_array = original_array.T
transposed_array

array([[1, 4],
       [2, 5],
       [3, 6]])